### ISSUE TITLE
Converter does not run in pipeline-runner

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/mmif-summarizer#1]
Used the following `docker-compose.ym`l file:

```yaml
version: '3'

services:

  pipeline:
    image: clams-pipeline
    container_name: clams_pipeline
    stdin_open: true
    tty: true
    volumes:
      - "/private/var/archive:/data"
      - "./:/app/host"
    ports:
      - '5000:5000'

  pbcore:
    image: mmif-pbcore-converter
    container_name: clams_pbcore
    build:
      dockerfile: Dockerfile
      context: ../mmif-pbcore-converter
    volumes:
      - "/private/var/archive:/data"
    ports:
      - '5001:5000'                                                                                           
```
